# Generated by Django 5.2 on 2025-04-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=100, unique=True, unique_for_date='date_time'),
        ),
    ]
