# Generated by Django 4.2.23 on 2025-06-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Комплект',
                'verbose_name_plural': 'Комплекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spare', models.ManyToManyField(through='cars.Kit', to='cars.spare')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='cars.machine'),
        ),
        migrations.AddField(
            model_name='kit',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='cars.spare'),
        ),
    ]
