# Generated by Django 5.2.3 on 2025-06-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='spare',
            field=models.ManyToManyField(through='cars.Kit', through_fields=('machine', 'spare'), to='cars.spare'),
        ),
    ]
