# Generated by Django 4.2.23 on 2025-08-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_machine_spare'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='image',
            field=models.ImageField(blank=True, upload_to='spares/'),
        ),
    ]
