# Generated by Django 4.2.23 on 2025-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
    ]
