# Generated by Django 4.2.23 on 2025-08-12 15:07

from django.db import migrations, models
import userAuth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_userprofile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, upload_to=userAuth.models.get_timestamp_path),
        ),
    ]
